# Generated by Django 4.1.5 on 2023-05-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_course_datas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('semail', models.EmailField(max_length=200)),
                ('smobile', models.CharField(max_length=10)),
                ('saddress', models.CharField(max_length=250)),
                ('scollege', models.CharField(max_length=250)),
                ('sdegree', models.CharField(max_length=250)),
                ('total_amount', models.IntegerField(max_length=250)),
                ('paid_amount', models.IntegerField(max_length=250)),
                ('due_amount', models.IntegerField(max_length=250)),
                ('scourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course_datas')),
            ],
        ),
    ]
